// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhzmcscuqdesqcbkyfmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoem1jc2N1cWRlc3FjYmt5Zm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODUxNTMsImV4cCI6MjA2NjI2MTE1M30.Us1odWP6o0UuThrnxkmGUDX885veq4llEvxyj5O1LAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);